name: fleeter
description: "This is an App that is designed to showcase my skills in Flutter, and dart"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  expandable: ^5.0.1
  blur: ^3.1.0
  build_runner: ^2.4.6
  math_expressions: ^2.4.0
  scidart: ^0.0.2-dev.12
  provider: ^6.0.5
  particles_fly: ^0.0.8
  path_provider: ^2.1.1
  flutter_local_notifications: ^8.1.1+3
  open_file: ^3.3.2
  archive: ^3.4.6
  file_picker: ^6.0.0
  process_run: ^0.13.1
  image: ^4.1.3
  path: ^1.8.3
  glass_kit: ^3.0.0
  video_compress: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/bg.jpg

